package hibernate.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the TeacherPromotions table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="TeacherPromotions"
 */
public abstract class BaseTeacherPromotions  implements Serializable {

	public static String PROP_TEACHER = "Teacher";
	public static String PROP_PROMOTION = "Promotion";
	public static String PROP_ID = "Id";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Integer _id;

	// many to one
	private hibernate.Users _teacher;
	private hibernate.Promotions _promotion;


	// constructors
	public BaseTeacherPromotions () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseTeacherPromotions (java.lang.Integer _id) {
		this.setId(_id);
		initialize();
	}

	/**
	 * Constructor for required fields
	 */
	public BaseTeacherPromotions (
		java.lang.Integer _id,
		hibernate.Users _teacher,
		hibernate.Promotions _promotion) {

		this.setId(_id);
		this.setTeacher(_teacher);
		this.setPromotion(_promotion);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="increment"
     *  column="Id"
     */
	public java.lang.Integer getId () {
		return _id;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _id the new ID
	 */
	public void setId (java.lang.Integer _id) {
		this._id = _id;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
     * @hibernate.property
     *  column=TeacherId
	 * not-null=true
	 */
	public hibernate.Users getTeacher () {
		return this._teacher;
	}

	/**
	 * Set the value related to the column: TeacherId
	 * @param _teacher the TeacherId value
	 */
	public void setTeacher (hibernate.Users _teacher) {
		this._teacher = _teacher;
	}


	/**
     * @hibernate.property
     *  column=PromotionId
	 * not-null=true
	 */
	public hibernate.Promotions getPromotion () {
		return this._promotion;
	}

	/**
	 * Set the value related to the column: PromotionId
	 * @param _promotion the PromotionId value
	 */
	public void setPromotion (hibernate.Promotions _promotion) {
		this._promotion = _promotion;
	}


	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof hibernate.base.BaseTeacherPromotions)) return false;
		else {
			hibernate.base.BaseTeacherPromotions mObj = (hibernate.base.BaseTeacherPromotions) obj;
			if (null == this.getId() || null == mObj.getId()) return false;
			else return (this.getId().equals(mObj.getId()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getId()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getId().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}