package hibernate.base;

import net.sf.hibernate.Hibernate;
import net.sf.hibernate.Session;
import hibernate.dao.AnswersDAO;

/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an automatically generated DAO class which should not be edited.
 */
public abstract class BaseAnswersDAO extends hibernate.dao._RootDAO {

	public static AnswersDAO instance;

	/**
	 * Return a singleton of the DAO
	 */
	public static AnswersDAO getInstance () {
		if (null == instance) instance = new AnswersDAO();
		return instance;
	}

	/**
	 * hibernate.dao._RootDAO _RootDAO.getReferenceClass()
	 */
	public Class getReferenceClass () {
		return hibernate.Answers.class;
	}
	
	public hibernate.Answers load(java.lang.Integer key)
		throws net.sf.hibernate.HibernateException {
		return (hibernate.Answers) load(getReferenceClass(), key);
	}

	public hibernate.Answers load(java.lang.Integer key, Session s)
		throws net.sf.hibernate.HibernateException {
		return (hibernate.Answers) load(getReferenceClass(), key, s);
	}

	public hibernate.Answers loadInitialize(java.lang.Integer key, Session s) 
			throws net.sf.hibernate.HibernateException { 
		hibernate.Answers obj = load(key, s); 
		if (!Hibernate.isInitialized(obj)) {
			Hibernate.initialize(obj);
		} 
		return obj; 
	}

	/**
	 * Persist the given transient instance, first assigning a generated identifier. (Or using the current value
	 * of the identifier property if the assigned generator is used.) 
	 * @param answers a transient instance of a persistent class 
	 * @return the class identifier
	 */
	public java.lang.Integer save(hibernate.Answers answers)
		throws net.sf.hibernate.HibernateException {
		return (java.lang.Integer) super.save(answers);
	}

	/**
	 * Persist the given transient instance, first assigning a generated identifier. (Or using the current value
	 * of the identifier property if the assigned generator is used.) 
	 * Use the Session given.
	 * @param answers a transient instance of a persistent class
	 * @param s the Session
	 * @return the class identifier
	 */
	public java.lang.Integer save(hibernate.Answers answers, Session s)
		throws net.sf.hibernate.HibernateException {
		return (java.lang.Integer) super.save(answers, s);
	}

	/**
	 * Either save() or update() the given instance, depending upon the value of its identifier property. By default
	 * the instance is always saved. This behaviour may be adjusted by specifying an unsaved-value attribute of the
	 * identifier property mapping. 
	 * @param answers a transient instance containing new or updated state 
	 */
	public void saveOrUpdate(hibernate.Answers answers)
		throws net.sf.hibernate.HibernateException {
		super.saveOrUpdate(answers);
	}

	/**
	 * Either save() or update() the given instance, depending upon the value of its identifier property. By default the
	 * instance is always saved. This behaviour may be adjusted by specifying an unsaved-value attribute of the identifier
	 * property mapping. 
	 * Use the Session given.
	 * @param answers a transient instance containing new or updated state.
	 * @param s the Session.
	 */
	public void saveOrUpdate(hibernate.Answers answers, Session s)
		throws net.sf.hibernate.HibernateException {
		super.saveOrUpdate(answers, s);
	}

	/**
	 * Update the persistent state associated with the given identifier. An exception is thrown if there is a persistent
	 * instance with the same identifier in the current session.
	 * @param answers a transient instance containing updated state
	 */
	public void update(hibernate.Answers answers) 
		throws net.sf.hibernate.HibernateException {
		super.update(answers);
	}

	/**
	 * Update the persistent state associated with the given identifier. An exception is thrown if there is a persistent
	 * instance with the same identifier in the current session.
	 * Use the Session given.
	 * @param answers a transient instance containing updated state
	 * @param the Session
	 */
	public void update(hibernate.Answers answers, Session s)
		throws net.sf.hibernate.HibernateException {
		super.update(answers, s);
	}

	/**
	 * Remove a persistent instance from the datastore. The argument may be an instance associated with the receiving
	 * Session or a transient instance with an identifier associated with existing persistent state. 
	 * @param id the instance ID to be removed
	 */
	public void delete(java.lang.Integer id)
		throws net.sf.hibernate.HibernateException {
		super.delete(load(id));
	}

	/**
	 * Remove a persistent instance from the datastore. The argument may be an instance associated with the receiving
	 * Session or a transient instance with an identifier associated with existing persistent state. 
	 * Use the Session given.
	 * @param id the instance ID to be removed
	 * @param s the Session
	 */
	public void delete(java.lang.Integer id, Session s)
		throws net.sf.hibernate.HibernateException {
		super.delete(load(id, s), s);
	}

	/**
	 * Remove a persistent instance from the datastore. The argument may be an instance associated with the receiving
	 * Session or a transient instance with an identifier associated with existing persistent state. 
	 * @param answers the instance to be removed
	 */
	public void delete(hibernate.Answers answers)
		throws net.sf.hibernate.HibernateException {
		super.delete(answers);
	}

	/**
	 * Remove a persistent instance from the datastore. The argument may be an instance associated with the receiving
	 * Session or a transient instance with an identifier associated with existing persistent state. 
	 * Use the Session given.
	 * @param answers the instance to be removed
	 * @param s the Session
	 */
	public void delete(hibernate.Answers answers, Session s)
		throws net.sf.hibernate.HibernateException {
		super.delete(answers, s);
	}
	
	/**
	 * Re-read the state of the given instance from the underlying database. It is inadvisable to use this to implement
	 * long-running sessions that span many business tasks. This method is, however, useful in certain special circumstances.
	 * For example 
	 * <ul> 
	 * <li>where a database trigger alters the object state upon insert or update</li>
	 * <li>after executing direct SQL (eg. a mass update) in the same session</li>
	 * <li>after inserting a Blob or Clob</li>
	 * </ul>
	 */
	public void refresh (hibernate.Answers answers, Session s)
		throws net.sf.hibernate.HibernateException {
		super.refresh(answers, s);
	}

    public String getDefaultOrderProperty () {
		return null;
    }

}