package hibernate.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the QuestionAnswers table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="QuestionAnswers"
 */
public abstract class BaseQuestionAnswers  implements Serializable {

	public static String PROP_ANSWER = "Answer";
	public static String PROP_QUESTION = "Question";
	public static String PROP_ID = "Id";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Integer _id;

	// many to one
	private hibernate.Questions _question;
	private hibernate.Answers _answer;


	// constructors
	public BaseQuestionAnswers () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseQuestionAnswers (java.lang.Integer _id) {
		this.setId(_id);
		initialize();
	}

	/**
	 * Constructor for required fields
	 */
	public BaseQuestionAnswers (
		java.lang.Integer _id,
		hibernate.Questions _question,
		hibernate.Answers _answer) {

		this.setId(_id);
		this.setQuestion(_question);
		this.setAnswer(_answer);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="native"
     *  column="Id"
     */
	public java.lang.Integer getId () {
		return _id;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _id the new ID
	 */
	public void setId (java.lang.Integer _id) {
		this._id = _id;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
     * @hibernate.property
     *  column=QuestionId
	 * not-null=true
	 */
	public hibernate.Questions getQuestion () {
		return this._question;
	}

	/**
	 * Set the value related to the column: QuestionId
	 * @param _question the QuestionId value
	 */
	public void setQuestion (hibernate.Questions _question) {
		this._question = _question;
	}


	/**
     * @hibernate.property
     *  column=AnswerId
	 * not-null=true
	 */
	public hibernate.Answers getAnswer () {
		return this._answer;
	}

	/**
	 * Set the value related to the column: AnswerId
	 * @param _answer the AnswerId value
	 */
	public void setAnswer (hibernate.Answers _answer) {
		this._answer = _answer;
	}


	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof hibernate.base.BaseQuestionAnswers)) return false;
		else {
			hibernate.base.BaseQuestionAnswers mObj = (hibernate.base.BaseQuestionAnswers) obj;
			if (null == this.getId() || null == mObj.getId()) return false;
			else return (this.getId().equals(mObj.getId()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getId()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getId().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}