package hibernate.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the Answers table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="Answers"
 */
public abstract class BaseAnswers  implements Serializable {

	public static String PROP_VALUE = "Value";
	public static String PROP_TYPE = "Type";
	public static String PROP_ID = "Id";
	public static String PROP_IS_CORRECT = "IsCorrect";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Integer _id;

	// fields
	private java.lang.String _value;
	private java.lang.Integer _type;
	private boolean _isCorrect;

	// collections
	private java.util.Set _questionAnswersSet;
	private java.util.Set _studentAnswersSet;


	// constructors
	public BaseAnswers () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseAnswers (java.lang.Integer _id) {
		this.setId(_id);
		initialize();
	}

	/**
	 * Constructor for required fields
	 */
	public BaseAnswers (
		java.lang.Integer _id,
		java.lang.String _value,
		java.lang.Integer _type,
		boolean _isCorrect) {

		this.setId(_id);
		this.setValue(_value);
		this.setType(_type);
		this.setIsCorrect(_isCorrect);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="native"
     *  column="Id"
     */
	public java.lang.Integer getId () {
		return _id;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _id the new ID
	 */
	public void setId (java.lang.Integer _id) {
		this._id = _id;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: Value
	 */
	public java.lang.String getValue () {
		return _value;
	}

	/**
	 * Set the value related to the column: Value
	 * @param _value the Value value
	 */
	public void setValue (java.lang.String _value) {
		this._value = _value;
	}


	/**
	 * Return the value associated with the column: Type
	 */
	public java.lang.Integer getType () {
		return _type;
	}

	/**
	 * Set the value related to the column: Type
	 * @param _type the Type value
	 */
	public void setType (java.lang.Integer _type) {
		this._type = _type;
	}


	/**
	 * Return the value associated with the column: IsCorrect
	 */
	public boolean isIsCorrect () {
		return _isCorrect;
	}

	/**
	 * Set the value related to the column: IsCorrect
	 * @param _isCorrect the IsCorrect value
	 */
	public void setIsCorrect (boolean _isCorrect) {
		this._isCorrect = _isCorrect;
	}


	/**
	 * Return the value associated with the column: QuestionAnswersSet
	 */
	public java.util.Set getQuestionAnswersSet () {
		return this._questionAnswersSet;
	}

	/**
	 * Set the value related to the column: QuestionAnswersSet
	 * @param _questionAnswersSet the QuestionAnswersSet value
	 */
	public void setQuestionAnswersSet (java.util.Set _questionAnswersSet) {
		this._questionAnswersSet = _questionAnswersSet;
	}
	
	public void addToQuestionAnswersSet (Object obj) {
		if (null == this._questionAnswersSet) this._questionAnswersSet = new java.util.HashSet();
		this._questionAnswersSet.add(obj);
	}



	/**
	 * Return the value associated with the column: StudentAnswersSet
	 */
	public java.util.Set getStudentAnswersSet () {
		return this._studentAnswersSet;
	}

	/**
	 * Set the value related to the column: StudentAnswersSet
	 * @param _studentAnswersSet the StudentAnswersSet value
	 */
	public void setStudentAnswersSet (java.util.Set _studentAnswersSet) {
		this._studentAnswersSet = _studentAnswersSet;
	}
	
	public void addToStudentAnswersSet (Object obj) {
		if (null == this._studentAnswersSet) this._studentAnswersSet = new java.util.HashSet();
		this._studentAnswersSet.add(obj);
	}



	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof hibernate.base.BaseAnswers)) return false;
		else {
			hibernate.base.BaseAnswers mObj = (hibernate.base.BaseAnswers) obj;
			if (null == this.getId() || null == mObj.getId()) return false;
			else return (this.getId().equals(mObj.getId()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getId()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getId().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}