package hibernate.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the Promotions table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="Promotions"
 */
public abstract class BasePromotions  implements Serializable {

	public static String PROP_NAME = "Name";
	public static String PROP_ID = "Id";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Integer _id;

	// fields
	private java.lang.String _name;

	// collections
	private java.util.Set _teacherPromotionsSet;


	// constructors
	public BasePromotions () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BasePromotions (java.lang.Integer _id) {
		this.setId(_id);
		initialize();
	}

	/**
	 * Constructor for required fields
	 */
	public BasePromotions (
		java.lang.Integer _id,
		java.lang.String _name) {

		this.setId(_id);
		this.setName(_name);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="increment"
     *  column="Id"
     */
	public java.lang.Integer getId () {
		return _id;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _id the new ID
	 */
	public void setId (java.lang.Integer _id) {
		this._id = _id;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: Name
	 */
	public java.lang.String getName () {
		return _name;
	}

	/**
	 * Set the value related to the column: Name
	 * @param _name the Name value
	 */
	public void setName (java.lang.String _name) {
		this._name = _name;
	}


	/**
	 * Return the value associated with the column: TeacherPromotionsSet
	 */
	public java.util.Set getTeacherPromotionsSet () {
		return this._teacherPromotionsSet;
	}

	/**
	 * Set the value related to the column: TeacherPromotionsSet
	 * @param _teacherPromotionsSet the TeacherPromotionsSet value
	 */
	public void setTeacherPromotionsSet (java.util.Set _teacherPromotionsSet) {
		this._teacherPromotionsSet = _teacherPromotionsSet;
	}
	
	public void addToTeacherPromotionsSet (Object obj) {
		if (null == this._teacherPromotionsSet) this._teacherPromotionsSet = new java.util.HashSet();
		this._teacherPromotionsSet.add(obj);
	}



	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof hibernate.base.BasePromotions)) return false;
		else {
			hibernate.base.BasePromotions mObj = (hibernate.base.BasePromotions) obj;
			if (null == this.getId() || null == mObj.getId()) return false;
			else return (this.getId().equals(mObj.getId()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getId()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getId().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}