package hibernate.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the Users table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="Users"
 */
public abstract class BaseUsers  implements Serializable {

	public static String PROP_EMAIL = "Email";
	public static String PROP_PROMOTION = "Promotion";
	public static String PROP_PASSWORD = "Password";
	public static String PROP_FIRST_NAME = "FirstName";
	public static String PROP_ROLE = "Role";
	public static String PROP_ID = "Id";
	public static String PROP_LAST_NAME = "LastName";
	public static String PROP_BIRTH_DATE = "BirthDate";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Integer _id;

	// fields
	private java.lang.String _email;
	private java.lang.String _password;
	private java.lang.Integer _role;
	private java.lang.String _firstName;
	private java.lang.String _lastName;
	private java.util.Date _birthDate;

	// many to one
	private hibernate.Promotions _promotion;

	// collections
	private java.util.Set _userTestsSet;
	private java.util.Set _studentAnswersSet;
	private java.util.Set _teacherPromotionsSet;
	private java.util.Set _userQuestionsSet;
	private java.util.Set _testsSet;
	private java.util.Set _userSubjectsSet;


	// constructors
	public BaseUsers () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseUsers (java.lang.Integer _id) {
		this.setId(_id);
		initialize();
	}

	/**
	 * Constructor for required fields
	 */
	public BaseUsers (
		java.lang.Integer _id,
		hibernate.Promotions _promotion,
		java.lang.String _email,
		java.lang.String _password,
		java.lang.Integer _role,
		java.lang.String _firstName,
		java.lang.String _lastName,
		java.util.Date _birthDate) {

		this.setId(_id);
		this.setPromotion(_promotion);
		this.setEmail(_email);
		this.setPassword(_password);
		this.setRole(_role);
		this.setFirstName(_firstName);
		this.setLastName(_lastName);
		this.setBirthDate(_birthDate);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="increment"
     *  column="Id"
     */
	public java.lang.Integer getId () {
		return _id;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _id the new ID
	 */
	public void setId (java.lang.Integer _id) {
		this._id = _id;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: Email
	 */
	public java.lang.String getEmail () {
		return _email;
	}

	/**
	 * Set the value related to the column: Email
	 * @param _email the Email value
	 */
	public void setEmail (java.lang.String _email) {
		this._email = _email;
	}


	/**
	 * Return the value associated with the column: Password
	 */
	public java.lang.String getPassword () {
		return _password;
	}

	/**
	 * Set the value related to the column: Password
	 * @param _password the Password value
	 */
	public void setPassword (java.lang.String _password) {
		this._password = _password;
	}


	/**
	 * Return the value associated with the column: Role
	 */
	public java.lang.Integer getRole () {
		return _role;
	}

	/**
	 * Set the value related to the column: Role
	 * @param _role the Role value
	 */
	public void setRole (java.lang.Integer _role) {
		this._role = _role;
	}


	/**
	 * Return the value associated with the column: FirstName
	 */
	public java.lang.String getFirstName () {
		return _firstName;
	}

	/**
	 * Set the value related to the column: FirstName
	 * @param _firstName the FirstName value
	 */
	public void setFirstName (java.lang.String _firstName) {
		this._firstName = _firstName;
	}


	/**
	 * Return the value associated with the column: LastName
	 */
	public java.lang.String getLastName () {
		return _lastName;
	}

	/**
	 * Set the value related to the column: LastName
	 * @param _lastName the LastName value
	 */
	public void setLastName (java.lang.String _lastName) {
		this._lastName = _lastName;
	}


	/**
	 * Return the value associated with the column: BirthDate
	 */
	public java.util.Date getBirthDate () {
		return _birthDate;
	}

	/**
	 * Set the value related to the column: BirthDate
	 * @param _birthDate the BirthDate value
	 */
	public void setBirthDate (java.util.Date _birthDate) {
		this._birthDate = _birthDate;
	}


	/**
     * @hibernate.property
     *  column=PromotionId
	 * not-null=true
	 */
	public hibernate.Promotions getPromotion () {
		return this._promotion;
	}

	/**
	 * Set the value related to the column: PromotionId
	 * @param _promotion the PromotionId value
	 */
	public void setPromotion (hibernate.Promotions _promotion) {
		this._promotion = _promotion;
	}


	/**
	 * Return the value associated with the column: UserTestsSet
	 */
	public java.util.Set getUserTestsSet () {
		return this._userTestsSet;
	}

	/**
	 * Set the value related to the column: UserTestsSet
	 * @param _userTestsSet the UserTestsSet value
	 */
	public void setUserTestsSet (java.util.Set _userTestsSet) {
		this._userTestsSet = _userTestsSet;
	}
	
	public void addToUserTestsSet (Object obj) {
		if (null == this._userTestsSet) this._userTestsSet = new java.util.HashSet();
		this._userTestsSet.add(obj);
	}



	/**
	 * Return the value associated with the column: StudentAnswersSet
	 */
	public java.util.Set getStudentAnswersSet () {
		return this._studentAnswersSet;
	}

	/**
	 * Set the value related to the column: StudentAnswersSet
	 * @param _studentAnswersSet the StudentAnswersSet value
	 */
	public void setStudentAnswersSet (java.util.Set _studentAnswersSet) {
		this._studentAnswersSet = _studentAnswersSet;
	}
	
	public void addToStudentAnswersSet (Object obj) {
		if (null == this._studentAnswersSet) this._studentAnswersSet = new java.util.HashSet();
		this._studentAnswersSet.add(obj);
	}



	/**
	 * Return the value associated with the column: TeacherPromotionsSet
	 */
	public java.util.Set getTeacherPromotionsSet () {
		return this._teacherPromotionsSet;
	}

	/**
	 * Set the value related to the column: TeacherPromotionsSet
	 * @param _teacherPromotionsSet the TeacherPromotionsSet value
	 */
	public void setTeacherPromotionsSet (java.util.Set _teacherPromotionsSet) {
		this._teacherPromotionsSet = _teacherPromotionsSet;
	}
	
	public void addToTeacherPromotionsSet (Object obj) {
		if (null == this._teacherPromotionsSet) this._teacherPromotionsSet = new java.util.HashSet();
		this._teacherPromotionsSet.add(obj);
	}



	/**
	 * Return the value associated with the column: UserQuestionsSet
	 */
	public java.util.Set getUserQuestionsSet () {
		return this._userQuestionsSet;
	}

	/**
	 * Set the value related to the column: UserQuestionsSet
	 * @param _userQuestionsSet the UserQuestionsSet value
	 */
	public void setUserQuestionsSet (java.util.Set _userQuestionsSet) {
		this._userQuestionsSet = _userQuestionsSet;
	}
	
	public void addToUserQuestionsSet (Object obj) {
		if (null == this._userQuestionsSet) this._userQuestionsSet = new java.util.HashSet();
		this._userQuestionsSet.add(obj);
	}



	/**
	 * Return the value associated with the column: TestsSet
	 */
	public java.util.Set getTestsSet () {
		return this._testsSet;
	}

	/**
	 * Set the value related to the column: TestsSet
	 * @param _testsSet the TestsSet value
	 */
	public void setTestsSet (java.util.Set _testsSet) {
		this._testsSet = _testsSet;
	}
	
	public void addToTestsSet (Object obj) {
		if (null == this._testsSet) this._testsSet = new java.util.HashSet();
		this._testsSet.add(obj);
	}



	/**
	 * Return the value associated with the column: UserSubjectsSet
	 */
	public java.util.Set getUserSubjectsSet () {
		return this._userSubjectsSet;
	}

	/**
	 * Set the value related to the column: UserSubjectsSet
	 * @param _userSubjectsSet the UserSubjectsSet value
	 */
	public void setUserSubjectsSet (java.util.Set _userSubjectsSet) {
		this._userSubjectsSet = _userSubjectsSet;
	}
	
	public void addToUserSubjectsSet (Object obj) {
		if (null == this._userSubjectsSet) this._userSubjectsSet = new java.util.HashSet();
		this._userSubjectsSet.add(obj);
	}



	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof hibernate.base.BaseUsers)) return false;
		else {
			hibernate.base.BaseUsers mObj = (hibernate.base.BaseUsers) obj;
			if (null == this.getId() || null == mObj.getId()) return false;
			else return (this.getId().equals(mObj.getId()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getId()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getId().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}