package hibernate.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the UserTests table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="UserTests"
 */
public abstract class BaseUserTests  implements Serializable {

	public static String PROP_USER = "User";
	public static String PROP_TEST = "Test";
	public static String PROP_MARK = "Mark";
	public static String PROP_STATE = "State";
	public static String PROP_ID = "Id";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Integer _id;

	// fields
	private java.lang.Float _mark;
	private java.lang.Integer _state;

	// many to one
	private hibernate.Tests _test;
	private hibernate.Users _user;


	// constructors
	public BaseUserTests () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseUserTests (java.lang.Integer _id) {
		this.setId(_id);
		initialize();
	}

	/**
	 * Constructor for required fields
	 */
	public BaseUserTests (
		java.lang.Integer _id,
		hibernate.Tests _test,
		hibernate.Users _user,
		java.lang.Integer _state) {

		this.setId(_id);
		this.setTest(_test);
		this.setUser(_user);
		this.setState(_state);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="native"
     *  column="Id"
     */
	public java.lang.Integer getId () {
		return _id;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _id the new ID
	 */
	public void setId (java.lang.Integer _id) {
		this._id = _id;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: Mark
	 */
	public java.lang.Float getMark () {
		return _mark;
	}

	/**
	 * Set the value related to the column: Mark
	 * @param _mark the Mark value
	 */
	public void setMark (java.lang.Float _mark) {
		this._mark = _mark;
	}


	/**
	 * Return the value associated with the column: State
	 */
	public java.lang.Integer getState () {
		return _state;
	}

	/**
	 * Set the value related to the column: State
	 * @param _state the State value
	 */
	public void setState (java.lang.Integer _state) {
		this._state = _state;
	}


	/**
     * @hibernate.property
     *  column=TestId
	 * not-null=true
	 */
	public hibernate.Tests getTest () {
		return this._test;
	}

	/**
	 * Set the value related to the column: TestId
	 * @param _test the TestId value
	 */
	public void setTest (hibernate.Tests _test) {
		this._test = _test;
	}


	/**
     * @hibernate.property
     *  column=UserId
	 * not-null=true
	 */
	public hibernate.Users getUser () {
		return this._user;
	}

	/**
	 * Set the value related to the column: UserId
	 * @param _user the UserId value
	 */
	public void setUser (hibernate.Users _user) {
		this._user = _user;
	}


	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof hibernate.base.BaseUserTests)) return false;
		else {
			hibernate.base.BaseUserTests mObj = (hibernate.base.BaseUserTests) obj;
			if (null == this.getId() || null == mObj.getId()) return false;
			else return (this.getId().equals(mObj.getId()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getId()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getId().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}