package hibernate.dao;

import net.sf.hibernate.HibernateException;
import net.sf.hibernate.Session;
import net.sf.hibernate.Transaction;
import hibernate.HibernateUtil;
import hibernate.Promotions;
import hibernate.base.BasePromotionsDAO;

/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is the object class that relates to the Promotions table.
 * Any customizations belong here.
 */
public class PromotionsDAO extends BasePromotionsDAO {
	public Promotions CreatePromotion(String promotionName) throws HibernateException
	{
		
		Promotions promotion = new Promotions();
		promotion.setName(promotionName);
		try
		{
			HibernateUtil.currentSession().saveOrUpdate(promotion);
			return promotion;
		} catch (HibernateException e)
		{
			return null;
		}
	}
}