package hibernate.java;
// Generated Mar 12, 2015 7:14:43 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Promotions generated by hbm2java
 */
public class Promotions implements java.io.Serializable
{
	private static final long serialVersionUID = -1678740783583791864L;
	private int id;
	private String name;
	private Set<Users> userses = new HashSet<Users>(0);
	private Set<Users> userses_1 = new HashSet<Users>(0);
	private Set<TeacherPromotions> teacherPromotionses = new HashSet<TeacherPromotions>(
			0);

	public Promotions()
	{
	}

	public Promotions(int id, String name)
	{
		this.id = id;
		this.name = name;
	}

	public Promotions(int id, String name, Set<Users> userses,
			Set<Users> userses_1, Set<TeacherPromotions> teacherPromotionses)
	{
		this.id = id;
		this.name = name;
		this.userses = userses;
		this.userses_1 = userses_1;
		this.teacherPromotionses = teacherPromotionses;
	}

	public int getId()
	{
		return this.id;
	}

	public void setId(int id)
	{
		this.id = id;
	}

	public String getName()
	{
		return this.name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	public Set<Users> getUserses()
	{
		return this.userses;
	}

	public void setUserses(Set<Users> userses)
	{
		this.userses = userses;
	}

	public Set<Users> getUserses_1()
	{
		return this.userses_1;
	}

	public void setUserses_1(Set<Users> userses_1)
	{
		this.userses_1 = userses_1;
	}

	public Set<TeacherPromotions> getTeacherPromotionses()
	{
		return this.teacherPromotionses;
	}

	public void setTeacherPromotionses(
			Set<TeacherPromotions> teacherPromotionses)
	{
		this.teacherPromotionses = teacherPromotionses;
	}

}
