package hibernate.java;
// Generated Mar 12, 2015 7:14:43 PM by Hibernate Tools 4.0.0

/**
 * QuestionAnswers generated by hbm2java
 */
public class QuestionAnswers implements java.io.Serializable
{
	private static final long serialVersionUID = -6901535213780659959L;
	private int id;
	private Questions questions;
	private Answers answers;

	public QuestionAnswers()
	{
	}

	public QuestionAnswers(int id)
	{
		this.id = id;
	}

	public QuestionAnswers(int id, Questions questions, Answers answers)
	{
		this.id = id;
		this.questions = questions;
		this.answers = answers;
	}

	public int getId()
	{
		return this.id;
	}

	public void setId(int id)
	{
		this.id = id;
	}

	public Questions getQuestions()
	{
		return this.questions;
	}

	public void setQuestions(Questions questions)
	{
		this.questions = questions;
	}

	public Answers getAnswers()
	{
		return this.answers;
	}

	public void setAnswers(Answers answers)
	{
		this.answers = answers;
	}

}
