package hibernate.java;
// Generated Mar 12, 2015 7:14:43 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Questions generated by hbm2java
 */
public class Questions implements java.io.Serializable
{
	private static final long serialVersionUID = -650760658223888809L;
	private int id;
	private Categories categories;
	private String content;
	private BigDecimal ponderation;
	private Set<UserQuestions> userQuestionses = new HashSet<UserQuestions>(0);
	private Set<QuestionAnswers> questionAnswerses = new HashSet<QuestionAnswers>(
			0);

	public Questions()
	{
	}

	public Questions(int id, String content, BigDecimal ponderation)
	{
		this.id = id;
		this.content = content;
		this.ponderation = ponderation;
	}

	public Questions(int id, Categories categories, String content,
			BigDecimal ponderation, Set<UserQuestions> userQuestionses,
			Set<QuestionAnswers> questionAnswerses)
	{
		this.id = id;
		this.categories = categories;
		this.content = content;
		this.ponderation = ponderation;
		this.userQuestionses = userQuestionses;
		this.questionAnswerses = questionAnswerses;
	}

	public int getId()
	{
		return this.id;
	}

	public void setId(int id)
	{
		this.id = id;
	}

	public Categories getCategories()
	{
		return this.categories;
	}

	public void setCategories(Categories categories)
	{
		this.categories = categories;
	}

	public String getContent()
	{
		return this.content;
	}

	public void setContent(String content)
	{
		this.content = content;
	}

	public BigDecimal getPonderation()
	{
		return this.ponderation;
	}

	public void setPonderation(BigDecimal ponderation)
	{
		this.ponderation = ponderation;
	}

	public Set<UserQuestions> getUserQuestionses()
	{
		return this.userQuestionses;
	}

	public void setUserQuestionses(Set<UserQuestions> userQuestionses)
	{
		this.userQuestionses = userQuestionses;
	}

	public Set<QuestionAnswers> getQuestionAnswerses()
	{
		return this.questionAnswerses;
	}

	public void setQuestionAnswerses(Set<QuestionAnswers> questionAnswerses)
	{
		this.questionAnswerses = questionAnswerses;
	}

}
