package hibernate.java;
// Generated Mar 12, 2015 7:14:43 PM by Hibernate Tools 4.0.0

/**
 * StudentAnswers generated by hbm2java
 */
public class StudentAnswers implements java.io.Serializable
{
	private static final long serialVersionUID = 5724487479699265640L;
	private int id;
	private Answers answers;
	private Users users;
	private Tests tests;
	private byte isChecked;

	public StudentAnswers()
	{
	}

	public StudentAnswers(int id, byte isChecked)
	{
		this.id = id;
		this.isChecked = isChecked;
	}

	public StudentAnswers(int id, Answers answers, Users users, Tests tests,
			byte isChecked)
	{
		this.id = id;
		this.answers = answers;
		this.users = users;
		this.tests = tests;
		this.isChecked = isChecked;
	}

	public int getId()
	{
		return this.id;
	}

	public void setId(int id)
	{
		this.id = id;
	}

	public Answers getAnswers()
	{
		return this.answers;
	}

	public void setAnswers(Answers answers)
	{
		this.answers = answers;
	}

	public Users getUsers()
	{
		return this.users;
	}

	public void setUsers(Users users)
	{
		this.users = users;
	}

	public Tests getTests()
	{
		return this.tests;
	}

	public void setTests(Tests tests)
	{
		this.tests = tests;
	}

	public byte getIsChecked()
	{
		return this.isChecked;
	}

	public void setIsChecked(byte isChecked)
	{
		this.isChecked = isChecked;
	}

}
