package hibernate.java;
// Generated Mar 12, 2015 7:14:43 PM by Hibernate Tools 4.0.0

/**
 * TeacherPromotions generated by hbm2java
 */
public class TeacherPromotions implements java.io.Serializable
{
	private static final long serialVersionUID = 3114884621259700446L;
	private int id;
	private Users users;
	private Promotions promotions;

	public TeacherPromotions()
	{
	}

	public TeacherPromotions(int id)
	{
		this.id = id;
	}

	public TeacherPromotions(int id, Users users, Promotions promotions)
	{
		this.id = id;
		this.users = users;
		this.promotions = promotions;
	}

	public int getId()
	{
		return this.id;
	}

	public void setId(int id)
	{
		this.id = id;
	}

	public Users getUsers()
	{
		return this.users;
	}

	public void setUsers(Users users)
	{
		this.users = users;
	}

	public Promotions getPromotions()
	{
		return this.promotions;
	}

	public void setPromotions(Promotions promotions)
	{
		this.promotions = promotions;
	}

}
