package hibernate.java;
// Generated Mar 12, 2015 7:14:43 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Tests generated by hbm2java
 */
public class Tests implements java.io.Serializable
{
	private static final long serialVersionUID = 1625076887273427580L;
	private int id;
	private Subjects subjects;
	private Users users;
	private byte isValidated;
	private Date endDate;
	private Date startDate;
	private Integer duration;
	private String title;
	private Set<UserTests> userTestses = new HashSet<UserTests>(0);
	private Set<StudentAnswers> studentAnswerses = new HashSet<StudentAnswers>(
			0);

	public Tests()
	{
	}

	public Tests(int id, byte isValidated, Date endDate, Date startDate,
			String title)
	{
		this.id = id;
		this.isValidated = isValidated;
		this.endDate = endDate;
		this.startDate = startDate;
		this.title = title;
	}

	public Tests(int id, Subjects subjects, Users users, byte isValidated,
			Date endDate, Date startDate, Integer duration, String title,
			Set<UserTests> userTestses, Set<StudentAnswers> studentAnswerses)
	{
		this.id = id;
		this.subjects = subjects;
		this.users = users;
		this.isValidated = isValidated;
		this.endDate = endDate;
		this.startDate = startDate;
		this.duration = duration;
		this.title = title;
		this.userTestses = userTestses;
		this.studentAnswerses = studentAnswerses;
	}

	public int getId()
	{
		return this.id;
	}

	public void setId(int id)
	{
		this.id = id;
	}

	public Subjects getSubjects()
	{
		return this.subjects;
	}

	public void setSubjects(Subjects subjects)
	{
		this.subjects = subjects;
	}

	public Users getUsers()
	{
		return this.users;
	}

	public void setUsers(Users users)
	{
		this.users = users;
	}

	public byte getIsValidated()
	{
		return this.isValidated;
	}

	public void setIsValidated(byte isValidated)
	{
		this.isValidated = isValidated;
	}

	public Date getEndDate()
	{
		return this.endDate;
	}

	public void setEndDate(Date endDate)
	{
		this.endDate = endDate;
	}

	public Date getStartDate()
	{
		return this.startDate;
	}

	public void setStartDate(Date startDate)
	{
		this.startDate = startDate;
	}

	public Integer getDuration()
	{
		return this.duration;
	}

	public void setDuration(Integer duration)
	{
		this.duration = duration;
	}

	public String getTitle()
	{
		return this.title;
	}

	public void setTitle(String title)
	{
		this.title = title;
	}

	public Set<UserTests> getUserTestses()
	{
		return this.userTestses;
	}

	public void setUserTestses(Set<UserTests> userTestses)
	{
		this.userTestses = userTestses;
	}

	public Set<StudentAnswers> getStudentAnswerses()
	{
		return this.studentAnswerses;
	}

	public void setStudentAnswerses(Set<StudentAnswers> studentAnswerses)
	{
		this.studentAnswerses = studentAnswerses;
	}

}
