package hibernate.java;
// Generated Mar 12, 2015 7:14:43 PM by Hibernate Tools 4.0.0

/**
 * UserSubjects generated by hbm2java
 */
public class UserSubjects implements java.io.Serializable
{
	private static final long serialVersionUID = -7992063284622883156L;
	private int id;
	private Subjects subjects;
	private Users users;

	public UserSubjects()
	{
	}

	public UserSubjects(int id)
	{
		this.id = id;
	}

	public UserSubjects(int id, Subjects subjects, Users users)
	{
		this.id = id;
		this.subjects = subjects;
		this.users = users;
	}

	public int getId()
	{
		return this.id;
	}

	public void setId(int id)
	{
		this.id = id;
	}

	public Subjects getSubjects()
	{
		return this.subjects;
	}

	public void setSubjects(Subjects subjects)
	{
		this.subjects = subjects;
	}

	public Users getUsers()
	{
		return this.users;
	}

	public void setUsers(Users users)
	{
		this.users = users;
	}

}
