package hibernate.java;
// Generated Mar 12, 2015 7:14:43 PM by Hibernate Tools 4.0.0

/**
 * UserQuestions generated by hbm2java
 */
public class UserQuestions implements java.io.Serializable
{
	private static final long serialVersionUID = -8582064234292160923L;
	private int id;
	private Questions questions;
	private Users users;

	public UserQuestions()
	{
	}

	public UserQuestions(int id)
	{
		this.id = id;
	}

	public UserQuestions(int id, Questions questions, Users users)
	{
		this.id = id;
		this.questions = questions;
		this.users = users;
	}

	public int getId()
	{
		return this.id;
	}

	public void setId(int id)
	{
		this.id = id;
	}

	public Questions getQuestions()
	{
		return this.questions;
	}

	public void setQuestions(Questions questions)
	{
		this.questions = questions;
	}

	public Users getUsers()
	{
		return this.users;
	}

	public void setUsers(Users users)
	{
		this.users = users;
	}

}
