package hibernate.java;
// Generated Mar 12, 2015 7:14:43 PM by Hibernate Tools 4.0.0

/**
 * UserTests generated by hbm2java
 */
public class UserTests implements java.io.Serializable
{
	private static final long serialVersionUID = 6425690899034093660L;
	private int id;
	private Tests tests;
	private Users users;
	private Double mark;
	private int state;

	public UserTests()
	{
	}

	public UserTests(int id, int state)
	{
		this.id = id;
		this.state = state;
	}

	public UserTests(int id, Tests tests, Users users, Double mark, int state)
	{
		this.id = id;
		this.tests = tests;
		this.users = users;
		this.mark = mark;
		this.state = state;
	}

	public int getId()
	{
		return this.id;
	}

	public void setId(int id)
	{
		this.id = id;
	}

	public Tests getTests()
	{
		return this.tests;
	}

	public void setTests(Tests tests)
	{
		this.tests = tests;
	}

	public Users getUsers()
	{
		return this.users;
	}

	public void setUsers(Users users)
	{
		this.users = users;
	}

	public Double getMark()
	{
		return this.mark;
	}

	public void setMark(Double mark)
	{
		this.mark = mark;
	}

	public int getState()
	{
		return this.state;
	}

	public void setState(int state)
	{
		this.state = state;
	}

}
